### PR TITLE
Feature: Enable defining Axios interceptors during module registration

### PR DESCRIPTION
**Pull request by keawade**
Howdy @jasonraimondi!

I've been using your package for a while in my work (Thanks, btw! Glad to see someone else annoyed by `@nestjs/axios`'s use of observables :smile:). In my use I've found myself needing to configure [Axios interceptors](https://axios-http.com/docs/interceptors) and I haven't found a good place in the NestJS lifecycle to access and call `axiosRef.interceptors.request.use` cleanly. That's where this PR comes in as an attempt to expose interceptor configuration at module registration:

Changes:
- BREAKING: Updates module options type to be an interface of
  ```ts
  type AxiosModuleOptions = {
    config?: AxiosRequestConfig;
    interceptors?: {
      response?: {
        ...
      };
      request?: {
        ...
      };
    };
  };
  ```
  instead of
  ```ts
  type AxiosModuleOptions = AxiosRequestConfig;
  ```
  - As implemented this is a breaking change. Not a fan of breaking the existing API but it seemed the alternative would be to overload the existing type with something like `AxiosRequestConfig & { interceptors: { ... }` which felt worse to me.
- Refactors module setup to use NestJS's [configurable module builder](https://docs.nestjs.com/fundamentals/dynamic-modules#configurable-module-builder) so the interceptors could be registered without having to implement a big `registerAsync` method manually
  - Also helps ensure consistent sync/async module registration methods

Let me know if you have any questions about the changes or any preferences for how I approach this feature, etc. :smile:

### CODE REVIEW

**Comment by jasonraimondi** [comment]
@keawade This is awesome, great addition, thank you for your contribution! I'm just taking a quick glance at this now and it is looking good. I will take a better look at this over this weekend and get it merged.

**Comment by keawade** [comment]
I didn't update the documentation because I wanted to wait to hear back from you on whether or not that breaking change was okay with you.

Let me know on that and I'll take some time to update the docs before merge.

**Comment by jasonraimondi** [comment]
@keawade  I think the extensibility this brings is worth the breaking change and version bump to v2.x. The migration path seems straightforward enough that it shouldn't cause too much pain for users. 

Would you be able to add a changelog entry documenting the breaking change and new functionality? Once that's in place, I'd be happy to merge and deploy this as v2.0.0.

I've also pushed a fix to the main branch that resolves CI. If you merge or rebase (your preference) the test suite should run correctly.

**Comment by keawade** [comment]
Well I feel really silly for this but I got bamboozled and mixed up this package (`nestjs-axios-promise`) with [`nestjs-http-promise`](https://github.com/benhason1/nestjs-http-promise) lmao.

I think this patch is basically done so feel free to carry on with it. I'll be opening a patch with `nestjs-http-promise` later today as well haha.

**Comment by jasonraimondi** [comment]
Lmao dang I'm sorry man. Still appreciate your contribution 🙏. That package seems more full featured.

**Pull request merged**
